 ---
- hosts: nginx
  sudo: yes
  vars:
    - backend_server1: wp1.backend
    - backend_server2: wp2.backend
  roles:
    - frontend
    
- hosts: wordpress
  sudo: yes
  vars:
    - mysql_root_password: "lajhdjaskd64jgAKAHSGD"
    - wp_mysl_db: "wordpress"
    - wp_mysql_user: "wordpress"
    - wp_mysql_password: "ajsJAjsHaajs7"
    - wp_domain: "david.liberman.com"
    - wp_title: "Tanngeizer"
    - wp_admin: "admin"
    - wp_admin_password: "alksjd712fdUINA"
    - wp_admin_email: "admin@wp.com"
  roles: 
    - database
    - backend
