 ---
- hosts: nginx
  sudo: yes
  vars:
    - backend_server1: wp1.backend
    - backend_server2: wp2.backend
  roles:
    - frontend
    
- hosts: wordpress
  sudo: yes
  vars:
    - mysql_root_password: "lajhdjaskd64jgAKAHSGD"
    - wp_mysl_db: "wordpress"
    - wp_mysql_user: "wordpress"
    - wp_mysql_password: "ajsJAjsHaajs7"
  roles: 
    - database
    - backend