# roles/backend/tasks/main.yml
---
- name: update cache
  apt: update_cache=yes

- name: install apache+php
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - php-mysql
    - php
    - libapache2-mod-php
    - php-mcrypt
    - memcached
    - curl

- name: start apache
  service: name=apache2 state=started enabled=yes

- name: download wordpress
  get_url: url=https://wordpress.org/latest.tar.gz dest=/tmp/wordpress.tar.gz

- name: extract wordpress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no

- name: update apache default config
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

- name: change wordpress config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php

- name: create upload folder
  file: path=/var/www/wordpress/wp-content/uploads state=directory mode=0755 owner=www-data

- name: update wp config file
  lineinfile:
    dest=/var/www/wordpress/wp-config.php
    regexp="{{ item.regexp }}"
    line="{{ item.line}}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}

- name: download wp-cli package
  get_url: 
    url=https://github.com/wp-cli/builds/blob/gh-pages/deb/php-wpcli_1.5.0_all.deb
    dest=/root/wp-cli.deb

- name: install wp-cli
  apt: deb=/root/wp-cli.deb

- name: install wordpress admin role
  command: wp core install --url={{ wp_domain }} --title={{ wp_title }} --admin_user={{ wp_admin }} --admin_password={{ wp_admin_password }} --admin_email={{ wp_admin_email }}

- name: add wordpress users
  command: wp user create {{ wp_user_login }} {{ wp_user_email }} --role={{ wp_user_role }} --user_pass={{ wp_user_password }} --display_name={{ wp_user_visible_name }}
